title: Sumit's Blog
email: sksingh1997@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sks147.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _sks147
github_username:  sks147


# Build settings

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: _sks147
    github: sks147
    rss: rss
    # dribbble: jekyll
    facebook: sks147
    # flickr:   jekyll
    instagram: _sks147
    linkedin: sks147


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
markdown: kramdown
theme: minima

plugins:
 - jekyll-feed

sass:
  style: compressed

destination: public

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
